### ISSUE TITLE
App gets mute after a couple of songs

### ISSUE THREAD

**Issue by czrcbl** [xou816/spot#118]
**Describe the bug**
After a couple of songs, the app gets mute even tough the playback bar keeps advancing. 

**To Reproduce**
1. Select a album
2.  Start playback
3. After a couple of songs, there will be no more sound. 

**General information:**
 - Distribution: POP OS 20.10
 - Installation method [e. g. built from source, installed from Flathub...]: Flathub
 - Version [e.g. 0.1.0]: 0.1.8
 - Device used [e. g. desktop, phone...]: Desktop

**Stack trace:**
If applicable, run the application from a terminal and paste relevant log output.
```
flatpak run --env=RUST_BACKTRACE=full dev.alextren.Spot

home
album_0gkUcpkyW2SXN49Yktkf6F
search
album_55MZQrenomrTq0aQneC7Pi
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SendError("...")', /run/build/spot/cargo/vendor/librespot-playback-0.1.3/src/player.rs:277:61
stack backtrace:
   0:     0x562607d89cb0 - <unknown>
   1:     0x562607dad75c - <unknown>
   2:     0x562607d82892 - <unknown>
   3:     0x562607d8bf55 - <unknown>
   4:     0x562607d8baaa - <unknown>
   5:     0x562607d8c6f1 - <unknown>
   6:     0x562607d8c237 - <unknown>
   7:     0x562607d8a16c - <unknown>
   8:     0x562607d8c199 - <unknown>
   9:     0x562607daaf71 - <unknown>
  10:     0x562607daad93 - <unknown>
  11:     0x562607a6dc53 - <unknown>
  12:     0x56260763c248 - <unknown>
  13:     0x5626075e7d4b - <unknown>
  14:     0x562607640bce - <unknown>
  15:     0x562607595ba7 - <unknown>
  16:     0x5626075d353d - <unknown>
  17:     0x562607571e72 - <unknown>
  18:     0x5626075d366d - <unknown>
  19:     0x562607565c2d - <unknown>
  20:     0x562607622a17 - <unknown>
  21:     0x5626075e7fb0 - <unknown>
  22:     0x562607565a35 - <unknown>
  23:     0x562607613577 - <unknown>
  24:     0x5626075c4cb2 - <unknown>
  25:     0x5626075a6bac - <unknown>
  26:     0x5626075ea41a - <unknown>
  27:     0x562607d9466a - <unknown>
  28:     0x7fe3f3ba64d2 - <unknown>
  29:     0x7fe3f397e323 - __clone
  30:                0x0 - <unknown>

```

**Comment by xou816** [comment]
Hi! :)
I've seen someone mention this before but I haven't been able to reproduce it thus far :/
It seems to happen in librespot, there are a couple of bug reports there that *could* match, not sure. Is it happening with specific songs?

**Comment by czrcbl** [comment]
Hi,
It happened all the times I tried to play a album, after about 2 songs the app gets mute.

**Comment by xou816** [comment]
I'm not sure I'll be able to help much, but there are a few things we can try.

Could you install a debug build [from here](https://github.com/xou816/spot/actions/runs/613697088)? (see Artifacts at the bottom)

And run it like so `flatpak run --env='RUST_BACKTRACE=full' --branch=master  dev.alextren.Spot`

**Comment by czrcbl** [comment]
This time it took a while, but I was able to spot the problem, follows the stack trace:
```
home
album_0MlTOiC5ZYKFGeZ8h3D4rd
album_0MlTOiC5ZYKFGeZ8h3D4rd
album_55MZQrenomrTq0aQneC7Pi
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SendError("...")', /run/build/spot/cargo/vendor/librespot-playback-0.1.6/src/player.rs:277:61
stack backtrace:
   0:     0x55f02046d4c0 - std::backtrace_rs::backtrace::libunwind::trace::h25e12e0d899beba0
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55f02046d4c0 - std::backtrace_rs::backtrace::trace_unsynchronized::h70e61195d6ae3df6
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55f02046d4c0 - std::sys_common::backtrace::_print_fmt::hba93ab80d779695a
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55f02046d4c0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf092b5883b4b2e50
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55f020490f6c - core::fmt::write::hf68bc350a8f2f0dc
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/fmt/mod.rs:1078:17
   5:     0x55f020466062 - std::io::Write::write_fmt::hf66811b1bc767436
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/io/mod.rs:1517:15
   6:     0x55f02046f765 - std::sys_common::backtrace::_print::hd425a11bfe1f20f8
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55f02046f765 - std::sys_common::backtrace::print::h6d678795c1e61e13
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55f02046f765 - std::panicking::default_hook::{{closure}}::h78a02a4a0dee5e7e
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:208:50
   9:     0x55f02046f2ba - std::panicking::default_hook::h56eb7eda02f355a7
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:225:9
  10:     0x55f02046ff01 - std::panicking::rust_panic_with_hook::hb27ea14285131c61
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:591:17
  11:     0x55f02046fa47 - std::panicking::begin_panic_handler::{{closure}}::hc552fcee62aad17f
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:497:13
  12:     0x55f02046d97c - std::sys_common::backtrace::__rust_end_short_backtrace::hb9f0aa9a78e885a0
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55f02046f9a9 - rust_begin_unwind
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
  14:     0x55f02048e781 - core::panicking::panic_fmt::h12ac4570ea43d06f
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
  15:     0x55f02048e5a3 - core::option::expect_none_failed::h096fa60f757b7204
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:1268:5
  16:     0x55f01f636b02 - core::result::Result<T,E>::unwrap::hebca647dbdcaf7a1
                               at /usr/lib/sdk/rust-stable/lib/rustlib/src/rust/library/core/src/result.rs:973:23
  17:     0x55f01f608ab8 - librespot_playback::player::Player::command::h61c8b9bec2980620
                               at /run/build/spot/cargo/vendor/librespot-playback-0.1.6/src/player.rs:277:9
  18:     0x55f01f608bb7 - librespot_playback::player::Player::load::h6e05006510be4197
                               at /run/build/spot/cargo/vendor/librespot-playback-0.1.6/src/player.rs:282:9
  19:     0x55f01ef34d4f - spot::app::backend::player::SpotifyPlayer::handle::{{closure}}::h5cd0c78b29c38b4c
                               at /run/build/spot/src/app/backend/player.rs:94:17
  20:     0x55f01f14cf39 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h886665f57c80f6da
                               at /usr/lib/sdk/rust-stable/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  21:     0x55f01ef3684c - spot::app::backend::player::SpotifyPlayer::start::{{closure}}::{{closure}}::{{closure}}::he7faaa61f60aaef3
                               at /run/build/spot/src/app/backend/player.rs:141:23
  22:     0x55f01f150379 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hfb2312170fa7183c
                               at /usr/lib/sdk/rust-stable/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  23:     0x55f01f017080 - <futures_util::stream::stream::for_each::ForEach<St,Fut,F> as core::future::future::Future>::poll::h1a6576f15a6e68fc
                               at /run/build/spot/cargo/vendor/futures-util-0.3.12/src/stream/stream/for_each.rs:69:24
  24:     0x55f01ef36cf5 - spot::app::backend::player::SpotifyPlayer::start::{{closure}}::hc9c36d38325dd754
                               at /run/build/spot/src/app/backend/player.rs:139:9
  25:     0x55f01f14a909 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h3eda57d2c76d7b9b
                               at /usr/lib/sdk/rust-stable/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  26:     0x55f01ef80c5c - <core::pin::Pin<P> as core::future::future::Future>::poll::h0242c44c1e8c0fd0
                               at /usr/lib/sdk/rust-stable/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
  27:     0x55f01ef7fba3 - <F as futures_core::future::TryFuture>::try_poll::hc85848b29f03df44
                               at /run/build/spot/cargo/vendor/futures-core-0.3.12/src/future.rs:83:9
  28:     0x55f01f0da983 - <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll::{{closure}}::h4dee0c1e3b3ea2ed
                               at /run/build/spot/cargo/vendor/futures-util-0.3.12/src/compat/compat03as01.rs:122:54
  29:     0x55f01f0da75d - futures_util::compat::compat03as01::with_context::hb19b73639a46bd54
                               at /run/build/spot/cargo/vendor/futures-util-0.3.12/src/compat/compat03as01.rs:224:5
  30:     0x55f01f0da95e - <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll::h142678adbeb81960
                               at /run/build/spot/cargo/vendor/futures-util-0.3.12/src/compat/compat03as01.rs:122:9
  31:     0x55f01f0f97be - futures::task_impl::Spawn<T>::poll_future_notify::{{closure}}::h8c32b870dd6d3924
                               at /run/build/spot/cargo/vendor/futures-0.1.30/src/task_impl/mod.rs:329:45
  32:     0x55f01f0f9dbe - futures::task_impl::Spawn<T>::enter::{{closure}}::h95561cc52eaf7ec9
                               at /run/build/spot/cargo/vendor/futures-0.1.30/src/task_impl/mod.rs:399:27
  33:     0x55f01ef97c83 - futures::task_impl::std::set::hdb8a60d46c0a7425
                               at /run/build/spot/cargo/vendor/futures-0.1.30/src/task_impl/std/mod.rs:86:13
  34:     0x55f01f0f99af - futures::task_impl::Spawn<T>::enter::h5f7835aa041c751f
                               at /run/build/spot/cargo/vendor/futures-0.1.30/src/task_impl/mod.rs:399:9
  35:     0x55f01f0f94b8 - futures::task_impl::Spawn<T>::poll_fn_notify::h8dae81d741748fe1
                               at /run/build/spot/cargo/vendor/futures-0.1.30/src/task_impl/mod.rs:291:9
  36:     0x55f01f0f9758 - futures::task_impl::Spawn<T>::poll_future_notify::hed43c9f6f9e0b2d6
                               at /run/build/spot/cargo/vendor/futures-0.1.30/src/task_impl/mod.rs:329:9
  37:     0x55f01f10f1ca - tokio_core::reactor::Core::run::{{closure}}::{{closure}}::{{closure}}::{{closure}}::{{closure}}::h7354deeb50af0d23
                               at /run/build/spot/cargo/vendor/tokio-core-0.1.18/src/reactor/mod.rs:237:53
  38:     0x55f01ef3f5a9 - futures::future::lazy::Lazy<F,R>::get::h2ad9f5d7dc791d38
                               at /run/build/spot/cargo/vendor/futures-0.1.30/src/future/lazy.rs:64:59
  39:     0x55f01ef3f6ee - <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll::hbb1153f27ded9296
                               at /run/build/spot/cargo/vendor/futures-0.1.30/src/future/lazy.rs:82:9
  40:     0x55f01f0f977e - futures::task_impl::Spawn<T>::poll_future_notify::{{closure}}::h40b91fcc8bf11b8c
                               at /run/build/spot/cargo/vendor/futures-0.1.30/src/task_impl/mod.rs:329:45
  41:     0x55f01f0f9d5e - futures::task_impl::Spawn<T>::enter::{{closure}}::h50de49d523ab5733
                               at /run/build/spot/cargo/vendor/futures-0.1.30/src/task_impl/mod.rs:399:27
  42:     0x55f01ef979f3 - futures::task_impl::std::set::h74766be0e1507c31
                               at /run/build/spot/cargo/vendor/futures-0.1.30/src/task_impl/std/mod.rs:86:13
  43:     0x55f01f0f989f - futures::task_impl::Spawn<T>::enter::h5a736886bc0d272b
                               at /run/build/spot/cargo/vendor/futures-0.1.30/src/task_impl/mod.rs:399:9
  44:     0x55f01f0f9418 - futures::task_impl::Spawn<T>::poll_fn_notify::h88bcfa17464c84cf
                               at /run/build/spot/cargo/vendor/futures-0.1.30/src/task_impl/mod.rs:291:9
  45:     0x55f01f0f96f8 - futures::task_impl::Spawn<T>::poll_future_notify::h0d386b0d6e458756
                               at /run/build/spot/cargo/vendor/futures-0.1.30/src/task_impl/mod.rs:329:9
  46:     0x55f01f0e0cf7 - tokio_current_thread::Entered<P>::block_on::{{closure}}::hcf8bd7cf350c6ea9
                               at /run/build/spot/cargo/vendor/tokio-current-thread-0.1.7/src/lib.rs:506:39
  47:     0x55f01f0e0953 - tokio_current_thread::Borrow<U>::enter::{{closure}}::{{closure}}::hf0ef8e9313ed041b
                               at /run/build/spot/cargo/vendor/tokio-current-thread-0.1.7/src/lib.rs:800:40
  48:     0x55f01f0e07ac - tokio_current_thread::CurrentRunner::set_spawn::hd0287c8723149809
                               at /run/build/spot/cargo/vendor/tokio-current-thread-0.1.7/src/lib.rs:841:9
  49:     0x55f01f0e0904 - tokio_current_thread::Borrow<U>::enter::{{closure}}::h30258474428b91c6
                               at /run/build/spot/cargo/vendor/tokio-current-thread-0.1.7/src/lib.rs:800:13
  50:     0x55f01efe3fd5 - std::thread::local::LocalKey<T>::try_with::ha55a574a1427f479
                               at /usr/lib/sdk/rust-stable/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  51:     0x55f01efe2abd - std::thread::local::LocalKey<T>::with::hd7e9a4c3cad80668
                               at /usr/lib/sdk/rust-stable/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  52:     0x55f01f0e0860 - tokio_current_thread::Borrow<U>::enter::h83b8cf36f75c78ec
                               at /run/build/spot/cargo/vendor/tokio-current-thread-0.1.7/src/lib.rs:798:9
  53:     0x55f01f0e0a40 - tokio_current_thread::Entered<P>::block_on::hda3ad8befa042147
                               at /run/build/spot/cargo/vendor/tokio-current-thread-0.1.7/src/lib.rs:503:23
  54:     0x55f01f10f16b - tokio_core::reactor::Core::run::{{closure}}::{{closure}}::{{closure}}::{{closure}}::h75e205dc46efd8a3
                               at /run/build/spot/cargo/vendor/tokio-core-0.1.18/src/reactor/mod.rs:235:33
  55:     0x55f01ef3f1a1 - tokio_timer::timer::handle::with_default::h07e2a5d063b9f7ff
                               at /run/build/spot/cargo/vendor/tokio-timer-0.2.13/src/timer/handle.rs:74:5
  56:     0x55f01f10f0d4 - tokio_core::reactor::Core::run::{{closure}}::{{closure}}::{{closure}}::h5d9e2469dbd9a7c0
                               at /run/build/spot/cargo/vendor/tokio-core-0.1.18/src/reactor/mod.rs:234:29
  57:     0x55f01f0408a1 - tokio_executor::global::with_default::{{closure}}::h27969b26e2dec6d8
                               at /run/build/spot/cargo/vendor/tokio-executor-0.1.10/src/global.rs:221:9
  58:     0x55f01efe48ba - std::thread::local::LocalKey<T>::try_with::hcb8c1439ec74c1f7
                               at /usr/lib/sdk/rust-stable/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  59:     0x55f01efe22f7 - std::thread::local::LocalKey<T>::with::h460b945e76e5719b
                               at /usr/lib/sdk/rust-stable/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  60:     0x55f01f040769 - tokio_executor::global::with_default::h2be455e3e7503ae7
                               at /run/build/spot/cargo/vendor/tokio-executor-0.1.10/src/global.rs:190:5
  61:     0x55f01f10f08d - tokio_core::reactor::Core::run::{{closure}}::{{closure}}::h8007b61a6b6dfd7d
                               at /run/build/spot/cargo/vendor/tokio-core-0.1.18/src/reactor/mod.rs:233:25
  62:     0x55f01ef3f26a - tokio_reactor::with_default::h1b95a26558361f7a
                               at /run/build/spot/cargo/vendor/tokio-reactor-0.1.12/src/lib.rs:220:5
  63:     0x55f01f10f035 - tokio_core::reactor::Core::run::{{closure}}::h3d5abedef6530a82
                               at /run/build/spot/cargo/vendor/tokio-core-0.1.18/src/reactor/mod.rs:232:21
  64:     0x55f01ef1b578 - scoped_tls::ScopedKey<T>::set::he4de2aedf383fc8a
                               at /run/build/spot/cargo/vendor/scoped-tls-0.1.2/src/lib.rs:155:9
  65:     0x55f01f10ecea - tokio_core::reactor::Core::run::h83efea2909dbe113
                               at /run/build/spot/cargo/vendor/tokio-core-0.1.18/src/reactor/mod.rs:231:32
  66:     0x55f01f0fc4be - spot::app::backend::start_player_service::{{closure}}::h11ea36b8bdd4518c
                               at /run/build/spot/src/app/backend/mod.rs:81:9
  67:     0x55f01f040a43 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf3ae501296db28f8
                               at /usr/lib/sdk/rust-stable/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  68:     0x55f01f0da313 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h962cc1cf82ed35a9
                               at /usr/lib/sdk/rust-stable/lib/rustlib/src/rust/library/std/src/thread/mod.rs:474:17
  69:     0x55f01ef85553 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h78e88cbb7248aeed
                               at /usr/lib/sdk/rust-stable/lib/rustlib/src/rust/library/std/src/panic.rs:322:9
  70:     0x55f01ef107a9 - std::panicking::try::do_call::hb65e05cbcc7b8dd4
                               at /usr/lib/sdk/rust-stable/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
  71:     0x55f01ef1097d - __rust_try
  72:     0x55f01ef104e0 - std::panicking::try::hc730ed09d2997276
                               at /usr/lib/sdk/rust-stable/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
  73:     0x55f01ef85923 - std::panic::catch_unwind::h8c08e85f71568ffb
                               at /usr/lib/sdk/rust-stable/lib/rustlib/src/rust/library/std/src/panic.rs:396:14
  74:     0x55f01f0da114 - std::thread::Builder::spawn_unchecked::{{closure}}::hf93364a5cb403b76
                               at /usr/lib/sdk/rust-stable/lib/rustlib/src/rust/library/std/src/thread/mod.rs:473:30
  75:     0x55f01f0853ae - core::ops::function::FnOnce::call_once{{vtable.shim}}::haebc2a516713052d
                               at /usr/lib/sdk/rust-stable/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  76:     0x55f020477e7a - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9ed215ba67984d70
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/alloc/src/boxed.rs:1328:9
  77:     0x55f020477e7a - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hcece06e1fe04906f
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/alloc/src/boxed.rs:1328:9
  78:     0x55f020477e7a - std::sys::unix::thread::Thread::new::thread_start::h6e82a4b7be15319a
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys/unix/thread.rs:71:17
  79:     0x7f876f87b4d2 - <unknown>
  80:     0x7f876f653323 - __clone
  81:                0x0 - <unknown>
```

**Comment by czrcbl** [comment]
Tested it after the last update, the problem seems to have gone away.

**Comment by xou816** [comment]
Actually happened to me one or two days ago, I'd be happy to fix it upstream but I can't reproduce it consistently :(

**Comment by czrcbl** [comment]
It happened again, but now it took longer, I was was able to listen to a full album plus some other songs.

**Comment by raaffaaeell** [comment]
I think this happens when librespot cant connect to the internet, this happens all the time to me when I activate my vpn, it'll crash, only way to get back is restarting the app

**Comment by czrcbl** [comment]
It happened with me with a steady connection also.

**Comment by Douile** [comment]
This happens for me with the official spotify client as well, so likely an issue with pipewire/pulseaudio or librespot.

**Comment by Douile** [comment]
Not sure if this is the same issue as I don't get a panic, but I can reliably reproduce a cut out and inability to play audio by locking and unlocking my display with light-locker. Checking pavucontrol shows that the application no longer has a playback stream.

Stack:
30caeaa6dabb94387d7d523b9904d77f71d75086 : manual build
pipewire 1:0.3.28-1 : audio backend
light-locker 1.9.0-4 : locking application

**Comment by MartinWallgren** [comment]
This happens everytime my computer resumes from hibernation. I have kill all spot processes and restart to get sound again.

**Comment by kevinwithat** [comment]
I’m having this issue as well now - would be happy to send reports as it happens quite frequently.

**Comment by xou816** [comment]
Hi! Sorry, I've not been following this very closely. There seems to be talks of reconnection issues in librespot (active discussion on that topic), which could explain the behavior with screens lockers, hibernation, etc I guess?
I'm not sure I can do much on my end, but stack traces are always welcome, and if we can find some easy-ish way to reproduce this consistently we could make a proper issue on the librespot side (if that's where the issue is of course).

**Comment by kevinwithat** [comment]
I want to help anyway I can so I'll research stack traces (I'm brand new to Linux). As for getting it reproduced, it happens almost every time I'm connected to my BT speakers and play through an album (just like OP). However, I also noticed it today when playing through a playlist - so librespot being the culprit sounds about right. So strange.

**Comment by yavko** [comment]
For me when it happens the pulseaudio stream disappears completely. I'm on pipewire btw.

**Comment by dCo3lh0** [comment]
damn, i like this client is light its spotify with steroids, but i cant use it because of this problem as well.

**Comment by yavko** [comment]
> damn, i like this client is light its spotify with steroids, but i cant use it because of this problem as well.

It doesn't bother me that much but yeah its annoying

**Comment by duncan-bayne** [comment]
I'm experiencing this as well. 

```
➜  ~ thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(Load(SpotifyId { id: 250588826709528476866023183837997428052, audio_type: Track }, true, 0))', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/librespot-playback-0.2.0/src/player.rs:334:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(...)', src/player/mod.rs:90:14
```

... then Spot goes silent, but the UI keeps on functioning _as though_ it were playing.  I can pause, play, skip, etc.

In my case I'm running Spot under Mobian GNU/Linux, on a PinePhone.  The period crashes render it essentially useless for Spotify music playback.

I think we should consider merging #416 into this issue as a duplicate.

**Comment by duncan-bayne** [comment]
> I was able to spot the problem

![spot](https://user-images.githubusercontent.com/65949/175227725-84cee89d-9dcc-4589-b8c4-e06f39e944ef.jpg)

**Comment by gloopsies** [comment]
I have the same problem. After a couple of songs I always stop hearing any sound until I restart Spot.
I am using Fedora Silverblue 36 and newest flatpak from Flathub.
These are the logs I get from running spot from terminal:
![image](https://user-images.githubusercontent.com/5102074/178941367-06e7527f-8fed-4128-bebf-2336d25ef6be.png)
If there are any more logs I could provide I would be happy to do so

**Comment by porkytin** [comment]
I know it's not ideal,  but spot could silently restart in the background when this error rises, and start playing the same playlist that was playing before restarting.

**Comment by pavelskipenes** [comment]
I get a different error output
```
❯ flatpak run --env='RUST_BACKTRACE=full' dev.alextren.Spot

(process:2): Adwaita-CRITICAL **: 19:26:26.942: adw_leaflet_set_visible_child: assertion 'contains_child' failed
[2023-12-01T18:40:15Z ERROR librespot_playback::player] Unable to load audio item: MercuryError
[2023-12-01T18:40:15Z ERROR librespot_core::session] Connection reset by peer (os error 104)
```
