### ISSUE TITLE
Cannot open empty playlists

### ISSUE THREAD

**Issue by sei0o** [xou816/spot#394]
**Describe the bug**
Clicking on an empty playlist, Spot panics because of zero division. According to the stacktrace, `SongBatch`'s `batch_size` is set to zero when `Page<T>` is [converted](https://github.com/xou816/spot/blob/be4ceb744354f74a3e006ab86cf9b423c4f8b76b/src/api/api_models.rs#L366) into `SongBatch`. I have no idea how `SongBatch` works, but zero-sized batches  seem misleading.

**To Reproduce**
1. Create an empty playlist (e.g. https://open.spotify.com/playlist/6ADEuR0Lj2eynRuflagSqt?si=05ea450ff8bb4b33)
2. Open it in Spot
3. *panic* 

**Expected behavior**
The playlist should be shown with an empty list. 
**General information:**
 - Distribution: Manjaro 
 - Installation method: Built from source
 - Version: 0.2.2
 - Device used: Desktop (i3wm)

**Stack trace:**

```
$ RUST_BACKTRACE=full ~/.local/bin/spot
thread 'main' panicked at 'attempt to divide by zero', src/app/models/core.rs:194:21
stack backtrace:
   0:     0x55946d677bec - std::backtrace_rs::backtrace::libunwind::trace::h3fea1eb2e0ba2ac9
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55946d677bec - std::backtrace_rs::backtrace::trace_unsynchronized::h849d83492cbc0d59
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55946d677bec - std::sys_common::backtrace::_print_fmt::he3179d37290f23d3
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55946d677bec - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h140f6925cad14324
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55946d69ce8c - core::fmt::write::h31b9cd1bedd7ea38
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/fmt/mod.rs:1150:17
   5:     0x55946d6708a5 - std::io::Write::write_fmt::h1fdf66f83f70913e
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/io/mod.rs:1667:15
   6:     0x55946d679800 - std::sys_common::backtrace::_print::he7ac492cd19c3189
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55946d679800 - std::sys_common::backtrace::print::hba20f8920229d8e8
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55946d679800 - std::panicking::default_hook::{{closure}}::h714d63979ae18678
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:210:50
   9:     0x55946d6793b7 - std::panicking::default_hook::hf1afb64e69563ca8
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:227:9
  10:     0x55946d679eb4 - std::panicking::rust_panic_with_hook::h02231a501e274a13
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:624:17
  11:     0x55946d679962 - std::panicking::begin_panic_handler::{{closure}}::h5b5e738edf361af7
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:519:13
  12:     0x55946d6780b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h601a115def7987b1
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55946d6798f9 - rust_begin_unwind
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
  14:     0x55946bdf7a41 - core::panicking::panic_fmt::h7a58c8fffc5559a4
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
  15:     0x55946bdf798d - core::panicking::panic::hcb81dec512b2768f
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:50:5
  16:     0x55946c241ba8 - spot::app::models::core::SongList::add_one::h5a77fb38257d27c0
                               at /home/sei0o/Devs/spot/src/app/models/core.rs:194:21
  17:     0x55946c241952 - spot::app::models::core::SongList::add::h6b38e897153924f7
                               at /home/sei0o/Devs/spot/src/app/models/core.rs:187:13
  18:     0x55946c240ac1 - spot::app::models::core::SongList::new_from_initial_batch::h95129d8cc745d05a
                               at /home/sei0o/Devs/spot/src/app/models/core.rs:84:9
  19:     0x55946c146490 - spot::api::api_models::<impl core::convert::From<spot::api::api_models::Playlist> for spot::app::models::main::PlaylistDescription>::from::h2081fc516647c7c5
                               at /home/sei0o/Devs/spot/src/api/api_models.rs:509:20
  20:     0x55946c17a05e - <T as core::convert::Into<U>>::into::hd86f57dee514e083
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/convert/mod.rs:540:9
  21:     0x55946be22f7e - <spot::api::cached_client::CachedSpotifyClient as spot::api::cached_client::SpotifyApiClient>::get_playlist::{{closure}}::h76097c6d67de3fb0
                               at /home/sei0o/Devs/spot/src/api/cached_client.rs:427:16
  22:     0x55946c0c5757 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hfc556beeef180313
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/future/mod.rs:80:19
  23:     0x55946c354f1b - <core::pin::Pin<P> as core::future::future::Future>::poll::h60258f9abdd380f1
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/future/future.rs:119:9
  24:     0x55946beb20ca - spot::app::components::playlist_details::playlist_details_model::PlaylistDetailsModel::load_playlist_info::{{closure}}::{{closure}}::hd74f4ae8bc2d0a52
                               at /home/sei0o/Devs/spot/src/app/components/playlist_details/playlist_details_model.rs:65:17
  25:     0x55946c0c12e9 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hca4526da0c0860c8
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/future/mod.rs:80:19
  26:     0x55946c35eead - spot::app::components::<impl dyn spot::app::dispatch::ActionDispatcher>::call_spotify_and_dispatch::{{closure}}::{{closure}}::hab00e3fcbbfe1fdc
                               at /home/sei0o/Devs/spot/src/app/components/mod.rs:86:61
  27:     0x55946c0c0291 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hb44a6b870438d59d
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/future/mod.rs:80:19
  28:     0x55946c36bcd5 - spot::app::components::<impl dyn spot::app::dispatch::ActionDispatcher>::call_spotify_and_dispatch_many::{{closure}}::hfe41031ebee79629
                               at /home/sei0o/Devs/spot/src/app/components/mod.rs:96:19
  29:     0x55946c0c2683 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hd8f37a62435341d1
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/future/mod.rs:80:19
  30:     0x55946c354abb - <core::pin::Pin<P> as core::future::future::Future>::poll::h1f9d991cf17d3645
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/future/future.rs:119:9
  31:     0x55946c1ed3ea - <spot::app::dispatch::ActionDispatcherImpl as spot::app::dispatch::ActionDispatcher>::dispatch_many_async::{{closure}}::hecf5fca32bf4aead
                               at /home/sei0o/Devs/spot/src/app/dispatch.rs:55:27
  32:     0x55946c0c593b - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hfe02620928e989a9
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/future/mod.rs:80:19
  33:     0x55946c355005 - <core::pin::Pin<P> as core::future::future::Future>::poll::h79fa592b2482b4c5
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/future/future.rs:119:9
  34:     0x55946c13786c - <futures_util::stream::stream::for_each::ForEach<St,Fut,F> as core::future::future::Future>::poll::h8717b7d4f7937b9b
                               at /home/sei0o/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.17/src/stream/stream/for_each.rs:68:24
  35:     0x55946d63c719 - <futures_task::future_obj::LocalFutureObj<T> as core::future::future::Future>::poll::h38d1a9391c40d1de
                               at /home/sei0o/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-task-0.3.17/src/future_obj.rs:84:18
  36:     0x55946d636e31 - <futures_task::future_obj::FutureObj<T> as core::future::future::Future>::poll::h9164bfc4109d97bd
                               at /home/sei0o/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-task-0.3.17/src/future_obj.rs:127:9
  37:     0x55946d62223b - <glib::main_context_futures::FutureWrapper as core::future::future::Future>::poll::h74ae0f466a1074b6
                               at /home/sei0o/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.14.8/src/main_context_futures.rs:30:41
  38:     0x55946d6227fe - glib::main_context_futures::TaskSource::poll::{{closure}}::h0e47a89e77f6c49f
                               at /home/sei0o/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.14.8/src/main_context_futures.rs:206:13
  39:     0x55946d629756 - glib::main_context::<impl glib::auto::main_context::MainContext>::with_thread_default::h530ac5ed833ec8bd
                               at /home/sei0o/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.14.8/src/main_context.rs:125:9
  40:     0x55946d622731 - glib::main_context_futures::TaskSource::poll::h8b72477c25a3ff72
                               at /home/sei0o/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.14.8/src/main_context_futures.rs:200:9
  41:     0x55946d62228e - glib::main_context_futures::TaskSource::dispatch::h20e276b2560a8c85
                               at /home/sei0o/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.14.8/src/main_context_futures.rs:66:34
  42:     0x7f7b2cc764dc - g_main_context_dispatch
  43:     0x7f7b2ccca749 - <unknown>
  44:     0x7f7b2cc73bc1 - g_main_context_iteration
  45:     0x7f7b2ce8b2ee - g_application_run
  46:     0x55946c307137 - <O as gio::application::ApplicationExtManual>::run_with_args::h1a9180e1aff309bb
                               at /home/sei0o/.cargo/registry/src/github.com-1ecc6299db9ec823/gio-0.14.8/src/application.rs:30:13
  47:     0x55946c307226 - <O as gio::application::ApplicationExtManual>::run::ha8fb84483830fc3f
                               at /home/sei0o/.cargo/registry/src/github.com-1ecc6299db9ec823/gio-0.14.8/src/application.rs:23:9
  48:     0x55946be64a90 - spot::main::{{closure}}::h3bd8ef1998715139
                               at /home/sei0o/Devs/spot/src/main.rs:69:9
  49:     0x55946bdfa747 - glib::main_context::<impl glib::auto::main_context::MainContext>::invoke_unsafe::trampoline::he34396bb1d7ca443
                               at /home/sei0o/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.14.8/src/main_context.rs:95:13
  50:     0x7f7b2cc75bd5 - g_main_context_invoke_full
  51:     0x55946c1441b2 - glib::main_context::<impl glib::auto::main_context::MainContext>::invoke_unsafe::he40b9ca0bb998f3a
                               at /home/sei0o/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.14.8/src/main_context.rs:102:9
  52:     0x55946c144231 - glib::main_context::<impl glib::auto::main_context::MainContext>::invoke_local_with_priority::h484fe36225a77585
                               at /home/sei0o/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.14.8/src/main_context.rs:81:13
  53:     0x55946c1440eb - glib::main_context::<impl glib::auto::main_context::MainContext>::invoke_local::hdd6ceabb23321c37
                               at /home/sei0o/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.14.8/src/main_context.rs:65:9
  54:     0x55946c009eeb - spot::main::h4640379fb142c1c4
                               at /home/sei0o/Devs/spot/src/main.rs:68:5
  55:     0x55946bf082eb - core::ops::function::FnOnce::call_once::h59fb028f65208e5d
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:227:5
  56:     0x55946c25db4e - std::sys_common::backtrace::__rust_begin_short_backtrace::h05452a63d2288156
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:125:18
  57:     0x55946be8e001 - std::rt::lang_start::{{closure}}::h22dd8704a20b313b
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:63:18
  58:     0x55946d67a4ba - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2790017aba790142
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:259:13
  59:     0x55946d67a4ba - std::panicking::try::do_call::hd5d0fbb7d2d2d85d
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
  60:     0x55946d67a4ba - std::panicking::try::h675520ee37b0fdf7
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
  61:     0x55946d67a4ba - std::panic::catch_unwind::h803430ea0284ce79
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
  62:     0x55946d67a4ba - std::rt::lang_start_internal::{{closure}}::h3a398a8154de3106
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:45:48
  63:     0x55946d67a4ba - std::panicking::try::do_call::hf60f106700df94b2
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
  64:     0x55946d67a4ba - std::panicking::try::hb2022d2bc87a9867
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
  65:     0x55946d67a4ba - std::panic::catch_unwind::hbf801c9d61f0c2fb
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
  66:     0x55946d67a4ba - std::rt::lang_start_internal::hdd488b91dc742b96
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:45:20
  67:     0x55946be8dfd0 - std::rt::lang_start::h723e2a94c6a01cde
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:62:5
  68:     0x55946c00a8cc - main
  69:     0x7f7b2c55eb25 - __libc_start_main
  70:     0x55946bdf824e - _start
  71:                0x0 - <unknown>
```

**Comment by xou816** [comment]
> 3. _panic_

indeed :rofl: 

Thanks for the report, I totally missed that!
