### ISSUE TITLE
Thread panic, causing no sound to be played. UI keeps running.

### ISSUE THREAD

**Issue by MortenLohne** [xou816/spot#416]
**Describe the bug**
I can't reproduce the bug exactly, but all sound output sometimes stops when navigating the UI (Only when changing songs, maybe?). UI continues to work as normal, but I have to restart the app to hear anything.

I get the following console error:
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(Load(SpotifyId { id: 188283750018304519635963874558152977448, audio_type: Track }, true, 0))', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/librespot-playback-0.2.0/src/player.rs:334:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(...)', src/player/mod.rs:90:14
```

**General information:**
 - Distribution: Ubuntu 20.04
 - Installation method: Snap
 - Version: 0.1.15
 - Device used: Desktop

**Stack trace:**

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(Load(SpotifyId { id: 188283750018304519635963874558152977448, audio_type: Track }, true, 0))', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/librespot-playback-0.2.0/src/player.rs:334:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(...)', src/player/mod.rs:90:14
```

**Comment by Diegovsky** [comment]
It happens to me if I don't play anyting for a while. Also when coming back from sleep.

**Comment by Louis9902** [comment]
I have the same Issue with Spot `` installed with flatpak:
This happens only when I come back from sleep/hibernate, but then my credentials are also broken, and I must log in again.
<details>
<summary>StackTrace</summary>

```
Jan 21 16:23:57 desktop-louis dev.alextren.Spot.desktop[76988]: [2022-01-21T15:23:57Z ERROR librespot_playback::player] Unable to load audio item: MercuryError
Jan 21 16:23:57 desktop-louis dev.alextren.Spot.desktop[76988]: [2022-01-21T15:23:57Z ERROR librespot_playback::player] Player Commands Error: channel closed
Jan 21 16:23:57 desktop-louis dev.alextren.Spot.desktop[76988]: [2022-01-21T15:23:57Z ERROR librespot_playback::player] Player Commands Error: channel closed
Jan 21 16:23:57 desktop-louis dev.alextren.Spot.desktop[76988]: [2022-01-21T15:23:57Z ERROR librespot_core::session] Connection reset by peer (os error 104)
Jan 21 16:24:04 desktop-louis dev.alextren.Spot.desktop[76988]: [2022-01-21T15:24:04Z ERROR librespot_playback::player] Player Commands Error: channel closed
Jan 21 16:24:04 desktop-louis dev.alextren.Spot.desktop[76988]: [2022-01-21T15:24:04Z ERROR librespot_playback::player] Player Commands Error: channel closed
Jan 21 16:24:11 desktop-louis dev.alextren.Spot.desktop[76988]: [2022-01-21T15:24:11Z ERROR librespot_playback::player] Player Commands Error: channel closed
Jan 21 16:24:11 desktop-louis dev.alextren.Spot.desktop[76988]: [2022-01-21T15:24:11Z ERROR librespot_playback::player] Player Commands Error: channel closed
Jan 21 16:24:14 desktop-louis dev.alextren.Spot.desktop[76988]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SendError((178, [0, 8, 0, 0, 0, 0, 0, 0, 0, 40, 1, 0, 1, 1, 38, 10, 158, 2, 104, 109, 58, 47, 47, 107, 101, 121, 109, 97, 115, 116, 1>
Jan 21 16:24:14 desktop-louis dev.alextren.Spot.desktop[76988]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Jan 21 16:24:14 desktop-louis dev.alextren.Spot.desktop[76988]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(...)', src/player/mod.rs:112:14
```

</details>

**Comment by xou816** [comment]
Might be similar to #118 which is (AFAICT) a librespot issue

**Comment by Diegovsky** [comment]
Oh yeah I tracked it down to librespot too but didn't know how to proceed.

Since you're doing the device integration control thing, I can look into it
